### ISSUE TITLE
Include Examples in docu

### ISSUE THREAD

**Issue by dglaeser** [dglaeser/gridformat#162]
One issue currently is that the link to the example folder in the start page of the api docu is broken. That is because it's a relative link in the repo. We could make that an absolute link - which has the downside that if one browses the files at a specific commit and clicks on the link, one ends up at a different commit. Or, we could include the examples & their markdown docu into the doxygen docs..

**Comment by IgorBaratta** [comment]
> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

It would be good if this issue could fixed for the Joss paper .
Even though I can find the examples in the repository, I can't seem to find the generated documentation.

**Comment by dglaeser** [comment]
@IgorBaratta, thanks a lot for your comment. 

> Even though I can find the examples in the repository, I can't seem to find the generated documentation.

This is because they are currently not included in the docs. They currently are meant to be read/used from the repo directly rather than the docs. But, the issue is that the link to the examples in the API documentation does not work because of the mentioned problem. Thanks for the reminder, I'll fix this asap.

**Comment by IgorBaratta** [comment]
Just fixing the link should be fine. 
Thanks for the quick reply.

**Comment by dglaeser** [comment]
@IgorBaratta, I pushed a fix with #220. I merged it s.t. the documentation gets deployed again. Would you mind checking and close the issue if you agree with this? Feel free to comment the merged PR in case you have any objections.

**Comment by IgorBaratta** [comment]
I can't close it. But I can confirm that the link is pointing to correct address now.

**Comment by danielskatz** [comment]
Note: this is part of https://github.com/openjournals/joss-reviews/issues/5778

**Comment by dglaeser** [comment]
@IgorBaratta, ok, thanks for the feedback!
