### ISSUE TITLE
[paper] Mention related works in other languages

### ISSUE THREAD

**Issue by timokoch** [dglaeser/gridformat#193]
At least `meshio` (Python package) is somewhat related although relying on internal mesh representations and being mainly used for converting mesh formats and printing information about meshes. I'm not aware of other approaches apart from that of course VTK implements writers and readers as well but no easy-to-use API for frameworks providing such data.

**Comment by dglaeser** [comment]
Hey @timokoch, I am trying to wrap up this project for submission. I added references to meshio and dune-vtk in a commit on the paper branch: b13cad3e

What are your thoughts?

**Comment by timokoch** [comment]
reads great
